#!/bin/bash

ffmpeg -v info -i rtsp://admin:Q260282Q@92.255.236.78:554/primary/h264 -c:v copy -c:a copy -bufsize 1835k -pix_fmt yuv420p -flags -global_header -hls_time 10 -hls_list_size 6 -hls_wrap 10 -start_number 1 /home/an/nginx/data/test.m3u8
